name: Release Drafter

on:
  push:
    # our release branch
    branches:
      - master

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - name: Drafting release
        id: release_drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASEDRAFTER_PAT }}
      - name: checkout to master
        uses: actions/checkout@master
      - name: Write release to markdown file
        run: |
          printf '%b\n' "---\nlayout: default\n---\n\n${{ steps.release_drafter.outputs.body }} " > ./docs/_releases/${{ steps.release_drafter.outputs.tag_name }}.md
      - name: Commit release mark down file
        run: |
          git config --local user.email "community@layer5.io"
          git config --local user.name "l5io"
          git add ./docs/_releases/${{ steps.release_drafter.outputs.tag_name }}.md
          git commit -m "Created release note file ${{ steps.release_drafter.outputs.tag_name }}.md"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.RELEASE_NOTES_PAT }}
